from pip._vendor.distlib.compat import raw_input
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time


class TwitterBot:
    def __init__(self, username, password):  # constructor
        self.username = username
        self.password = password
        self.bot = webdriver.Firefox()  # opens firefox in this case

    def login(self):  # this is not doing anything so far
        print("login section is alive")

    def createTwitterAccount(self):
        bot = self.bot
        bot.get("https://temp-mail.org/en/")
        time.sleep(5)
        bot.get("https://google.com")
        time.sleep(5)
        bot.get("https://temp-mail.org/en/")


if __name__ == '__main__':
    option = raw_input("Should I create a new Twitter Account?(Y/n): ")
    if option.upper() == 'Y':
        print("hello there")
    elif option.upper() == 'N':
        print("i am not a human")
    else:
        print("Please enter a normal value")


# websites used for this autogenerated-twitter like bot
# https://temp-mail.org/en/ temporary email address
# https://www.behindthename.com/random/ random name
# https://www.lastpass.com/password-generator random password
# https://twitter.com/explore twitter
