from pip._vendor.distlib.compat import raw_input
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time


class TwitterBot:
    def __init__(self, username, password):  # constructor
        self.username = username
        self.password = password
        self.bot = webdriver.Firefox()  # opens firefox in this case

    def login(self):  # this is not doing anything so far
        print("login section is alive")

    def createTwitterAccount(self):
        bot = self.bot
        bot.get("https://tempail.com/en/")
        time.sleep(3)  # waiting 3 seconds to connect to the site
        sign_up_mail = bot.find_element_by_xpath('//*[@id="eposta_adres"]').get_attribute(
            "value")  # getting the temp mail for the sign-up
        time.sleep(1)
        bot.get("https://www.behindthename.com/random/")
        time.sleep(3)
        bot.find_element_by_xpath(
            '/html/body/div[2]/div/div/center/form/div/input').click()  # clicking generate name button
        full_name = bot.find_element_by_xpath(
            '/html/body/div[2]/div/div/center/div[1]/span/a[1]').text + " " + bot.find_element_by_xpath(
            '/html/body/div[2]/div/div/center/div[1]/span/a[2]').text  # getting the full name from the proper website
        bot.get("https://nordpass.com/password-generator/")
        time.sleep(3)
        password = bot.find_element_by_xpath(
            '/html/body/div[1]/div[1]/div/div[1]/main/div/div[5]/section/div/div/div/div[1]/div/div[1]/div[1]').text
        print(password)


if __name__ == '__main__':
    bot = TwitterBot("", "")
    bot.createTwitterAccount()

# websites used for this autogenerated-twitter like bot
# https://tempail.com/en/ temporary email address
# https://www.behindthename.com/random/ random name
# https://nordpass.com/password-generator/ random password
# https://twitter.com/explore twitter
